### ISSUE TITLE
Wrong report in Jaseci Builtin `str` actions 

### ISSUE THREAD

**Issue by TharukaCkasthuri** [Jaseci-Labs/jaseci#949]
` .str::is_alnum` is to  Return true if the string is alpha numerical. but this action returns true only if the string only contains numerical values. 

Ex:

```
walker init{
    _string = "123 Hello World";
    report _string.str::is_alnum;
}
```

This reports `false`.

But 

```
walker init{
    _string = "123";
    report _string.str::is_alnum;
}
```

this reports `true`.

**Comment by twschutz** [comment]
I believe that this is the correct behavior for `.str::is_alnum`.

In your first example:
``` 
walker init{
    _string = "123 Hello World";
    report _string.str::is_alnum;
}
```
This reports `False` because the string "123 Hello World" is not alphanumeric as it has space characters " " that are not numerals or letters.

If you were to replace the whitespace from the string first:
```
walker init{
    _string = "123 Hello World";
    _string = _string.str::replace(" ", "");
   report _string;
   report _string.is_alnum;
}
```
This reports `"123HelloWorld", True`
